name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: voidsMark
          outputs: dist/snake.svg

      - name: Push Snake Animation to the output branch
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
