name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: jonasrtz/github-contribution-snake@v0.5.1
        with:
          output: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}

      - name: Commit and Push to output branch
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
